/* 
    This file was generated by "mtxrun --script "mtx-wtoc.lua" from the metapost cweb 
    files but now maintained as C file.
*/

# ifndef MPMATHSCALED_H
# define MPMATHSCALED_H 1

# include "mp.h"

math_data *mp_initialize_scaled_math (MP mp);

# endif

