/* 
    This file was generated by "mtxrun --script "mtx-wtoc.lua" from the metapost cweb 
    files but now maintained as C file.
*/

# include "mpmathbinary.h"

/*tex 
    We don't support the binary number format because no one uses it. We kept decimal 
    because it can also be handy at the \TEX\ end. 
*/

extern void tex_normal_warning (const char *t, const char *p);

math_data *mp_initialize_binary_math(MP mp)
{
    (void) (mp);
    tex_normal_warning("mplib", "binary mode is not available.");
    return NULL;
}
