.TH "mtx-kpse" "1" "01-01-2025" "version 1.00" "ConTeXt KPSE checking utility"
.SH NAME
 mtx-kpse - ConTeXt KPSE checking utility
.SH SYNOPSIS
.B mtxrun --script kpse [
.I OPTIONS ...
.B ] [
.I FILENAMES
.B ]
.SH DESCRIPTION
.B ConTeXt KPSE checking utility
.SH OPTIONS: BASIC
.TP
.B --progname
mandate, set the program name (e.g. pdftex)
.TP
.B --findfile
report the fully qualified path of the given file
.TP
.B --findfiles
report a list of all full names of the given file
.TP
.B --expandpath
expand the given path variable
.TP
.B --expandvar
expand a variable
.TP
.B --expandbraces
expand a complex variable specification
.TP
.B --varvalue
show the value of a variable
.TP
.B --readablefile
report if a file is readable
.TP
.B --filetypes
list all supported formats
.SH OPTIONS: ADDITIONAL
.TP
.B --format
format type
.TP
.B --path
path variable
.TP
.B --split
split result in lines
.SH AUTHOR
More information about ConTeXt and the tools that come with it can be found at:


.B "maillist:"
ntg-context@ntg.nl / http://www.ntg.nl/mailman/listinfo/ntg-context

.B "webpage:"
http://www.pragma-ade.nl / http://tex.aanhet.net

.B "wiki:"
http://contextgarden.net
