set(luapplib_sources
    luapplib/ppapi.h
    luapplib/pparray.c
    luapplib/pparray.h
    luapplib/ppconf.h
    luapplib/ppcrypt.c
    luapplib/ppcrypt.h
    luapplib/ppdict.c
    luapplib/ppdict.h
    luapplib/ppfilter.h
    luapplib/ppheap.c
    luapplib/ppheap.h
    luapplib/pplib.h
    luapplib/ppload.c
    luapplib/ppload.h
    luapplib/ppstream.c
    luapplib/ppstream.h
    luapplib/ppxref.c
    luapplib/ppxref.h
    luapplib/util/utilarm.h
    luapplib/util/utilbasexx.c
    luapplib/util/utilbasexx.h
    luapplib/util/utilcrypt.c
    luapplib/util/utilcrypt.h
    luapplib/util/utilcryptdef.h
    luapplib/util/utildecl.h
    luapplib/util/utilflate.c
    luapplib/util/utilflate.h
    luapplib/util/utilfpred.c
    luapplib/util/utilfpred.h
    luapplib/util/utiliof.c
    luapplib/util/utiliof.h
    luapplib/util/utillog.c
    luapplib/util/utillog.h
    luapplib/util/utillzw.c
    luapplib/util/utillzw.h
    luapplib/util/utilmd5.c
    luapplib/util/utilmd5.h
    luapplib/util/utilmem.c
    luapplib/util/utilmem.h
    luapplib/util/utilnumber.c
    luapplib/util/utilnumber.h
    luapplib/util/utilplat.h
    luapplib/util/utilsha.c
    luapplib/util/utilsha.h
)

add_library(luapplib STATIC ${luapplib_sources})

target_include_directories(luapplib
    PRIVATE
        luapplib
        luapplib/util
        libs/zlib/zlib-src
)
