set(texmeta_sources

    luatex-common.h

    font/luafont.h
    font/luafont.c
    font/texfont.h
    font/texfont.c

    lang/hnjalloc.h
    lang/hnjalloc.c
    lang/hyphen.h
    lang/hyphen.c
    lang/texlang.h
    lang/texlang.c

    lua/luatex-api.h

    lua/lcallbacklib.h
    lua/lcallbacklib.c
    lua/llanglib.h
    lua/llanglib.c
    lua/llualib.h
    lua/llualib.c
    lua/lnodelib.h
    lua/lnodelib.c
    lua/lstrlibext.c
    lua/ltexiolib.h
    lua/ltexiolib.c
    lua/ltexlib.h
    lua/ltexlib.c
    lua/ltokenlib.h
    lua/ltokenlib.c
    lua/luainit.h
    lua/luainit.c
    lua/luanode.h
    lua/luanode.c
    lua/luastuff.h
    lua/luastuff.c
    lua/lfontlib.c
    lua/ldecodelib.c
    lua/lpdfelib.c
    lua/lpdfscannerlib.c
    lua/liolibext.c
    lua/loslibext.c
    lua/lstatslib.c
    lua/luatoken.c

    luamplib/mplibstuff.h
    luamplib/mplibstuff.c
    luamplib/lmplib.c

    tex/align.h
    tex/align.c
    tex/arithmetic.h
    tex/arithmetic.c
    tex/buildpage.h
    tex/buildpage.c
    tex/commands.h
    tex/commands.c
    tex/conditional.h
    tex/conditional.c
    tex/directions.h
    tex/directions.c
    tex/dumpdata.h
    tex/dumpdata.c
    tex/equivalents.h
    tex/equivalents.c
    tex/errors.h
    tex/errors.c
    tex/expand.h
    tex/expand.c
    tex/extensions.h
    tex/extensions.c
    tex/inputstack.h
    tex/inputstack.c
    tex/linebreak.h
    tex/linebreak.c
    tex/mainbody.h
    tex/mainbody.c
    tex/maincontrol.h
    tex/maincontrol.c
    tex/mathcodes.c
    tex/mlist.c
    tex/mathcodes.h
    tex/memoryword.h
    tex/mlist.h
    tex/nesting.h
    tex/nesting.c
    tex/packaging.h
    tex/packaging.c
    tex/postlinebreak.h
    tex/postlinebreak.c
    tex/primitive.h
    tex/primitive.c
    tex/printing.h
    tex/printing.c
    tex/scanning.h
    tex/scanning.c
    tex/stringpool.h
    tex/stringpool.c
    tex/texdeffont.h
    tex/texdeffont.c
    tex/texfileio.h
    tex/texfileio.c
    tex/texmath.h
    tex/texmath.c
    tex/texnodes.h
    tex/texnodes.c
    tex/textcodes.h
    tex/textcodes.c
    tex/textoken.h
    tex/textoken.c

    utils/arithmetic.h
    utils/arithmetic.c
    utils/managed-sa.h
    utils/managed-sa.c
    utils/memory.h
    utils/memory.c
    utils/system.h
    utils/system.c
    utils/unistring.h
    utils/unistring.c
)

add_library(texmeta STATIC ${texmeta_sources})

target_include_directories(texmeta
    PRIVATE
        .
        libs/zlib/zlib-src
        luapplib/util
        lua54/src
)
