-- from the context garden

return {
    name = "mtx-install-imp-modules",
    version = "1.00",
    comment = "Third party modules",
    author = "Hans Hagen & others",
    copyright = "ConTeXt development team",
    lists = {
        ["pocketdiary"]       = { url = "modules", zips = { "Collection-of-calendars-based-on-PocketDiary-module.zip" } },
        ["collating"]         = { url = "modules", zips = { "Environment-for-collating-marks.zip" } },
        ["account"]           = { url = "modules", zips = { "t-account.zip" } },
        ["algorithmic"]       = { url = "modules", zips = { "t-algorithmic.zip" } },
        ["animation"]         = { url = "modules", zips = { "t-animation.zip" } },
        ["annotation"]        = { url = "modules", zips = { "t-annotation.zip" } },
        ["aquamints"]         = { url = "modules", zips = { "aquamints.zip" } },
        ["bibmod-doc"]        = { url = "modules", zips = { "bibmod-doc.zip" } },
     -- ["bnf-0.3"]           = { url = "modules", zips = { "t-bnf-0.3.zip" } },
        ["bnf"]               = { url = "modules", zips = { "t-bnf.zip" } },
        ["chromato"]          = { url = "modules", zips = { "t-chromato.zip" } },
        ["cmscbf"]            = { url = "modules", zips = { "t-cmscbf.zip" } },
        ["cmttbf"]            = { url = "modules", zips = { "t-cmttbf.zip" } },
        ["crossref"]          = { url = "modules", zips = { "t-crossref.zip" } },
        ["cyrillicnumbers"]   = { url = "modules", zips = { "t-cyrillicnumbers.zip" } },
        ["degrade"]           = { url = "modules", zips = { "t-degrade.zip" } },
        ["enigma"]            = { url = "modules", zips = { "enigma.zip" } },
        ["fancybreak"]        = { url = "modules", zips = { "t-fancybreak.zip" } },
        ["filter"]            = { url = "modules", zips = { "t-filter.zip" } },
        ["french"]            = { url = "modules", zips = { "t-french.zip" } },
        ["fullpage"]          = { url = "modules", zips = { "t-fullpage.zip" } },
        ["gantt"]             = { url = "modules", zips = { "t-gantt.zip" } },
        ["gfsdidot"]          = { url = "modules", zips = { "gfsdidot.zip" } },
        ["gm"]                = { url = "modules", zips = { "t-gm.zip" } },
        ["gnuplot"]           = { url = "modules", zips = { "t-gnuplot.zip" } },
        ["greek"]             = { url = "modules", zips = { "t-greek.zip" } },
        ["grph-downsample"]   = { url = "modules", zips = { "grph-downsample.lua.zip" } },
        ["gs"]                = { url = "modules", zips = { "t-gs.zip" } },
        ["high"]              = { url = "modules", zips = { "high.zip" } },
        ["inifile"]           = { url = "modules", zips = { "t-inifile.zip" } },
        ["karnaugh"]          = { url = "modules", zips = { "karnaugh.zip" } },
        ["layout"]            = { url = "modules", zips = { "t-layout.zip" } },
        ["letter"]            = { url = "modules", zips = { "t-letter.zip" } },
        ["letterspace"]       = { url = "modules", zips = { "t-letterspace.mkiv.zip" } },
        ["lettrine"]          = { url = "modules", zips = { "t-lettrine.zip" } },
        ["lua-widow-control"] = { url = "modules", zips = { "lua-widow-control.zip" } },
        ["mathsets"]          = { url = "modules", zips = { "t-mathsets.zip" } },
        ["metaducks"]         = { url = "modules", zips = { "metaducks.zip" } },
        ["pret-c.lua"]        = { url = "modules", zips = { "pret-c.lua.zip" } },
        ["rst"]               = { url = "modules", zips = { "t-rst.zip" } },
        ["rsteps"]            = { url = "modules", zips = { "t-rsteps.zip" } },
        ["simplebib"]         = { url = "modules", zips = { "t-simplebib.zip" } },
        ["simplefonts"]       = { url = "modules", zips = { "t-simplefonts.zip" } },
        ["simpleslides"]      = { url = "modules", zips = { "t-simpleslides.zip" } },
        ["stormfontsupport"]  = { url = "modules", zips = { "stormfontsupport.zip" } },
        ["sudoku"]            = { url = "modules", zips = { "sudoku.zip" } },
        ["taspresent"]        = { url = "modules", zips = { "t-taspresent.zip" } },
        ["texshow"]           = { url = "modules", zips = { "u-texshow.zip" } },
        ["title"]             = { url = "modules", zips = { "t-title.zip" } },
        ["transliterator"]    = { url = "modules", zips = { "t-transliterator.zip" } },
        ["typearea"]          = { url = "modules", zips = { "t-typearea.zip" } },
        ["typescripts"]       = { url = "modules", zips = { "t-typescripts.zip" } },
        ["urwgaramond"]       = { url = "modules", zips = { "f-urwgaramond.zip" } },
        ["urwgothic"]         = { url = "modules", zips = { "f-urwgothic.zip" } },
        ["vim"]               = { url = "modules", zips = { "t-vim.zip" } },
        ["visualcounter"]     = { url = "modules", zips = { "t-visualcounter.zip" } },
    }
}
